barco_venta:
    path:     /
    defaults: { _controller: BarcoBundle:Barco:barcos }
barco_detalle:
    path:     /detalle/{idBarco}
    defaults: { _controller: BarcoBundle:Barco:barcosDetalle }
barco_motor:
    path:     /motor
    defaults: { _controller: BarcoBundle:Barco:barcosMotor }
barco_add:
    path:     /addBarco
    defaults: { _controller: BarcoBundle:Barco:addBarcos }
barco_update:
    path:     /updateBarco/{idBarco}
    defaults: { _controller: BarcoBundle:Barco:actualizarBarco }
