barco_homepage:
    path:     /
    defaults: { _controller: BarcoBundle:Default:index }
barco_register:
    path:     /register
    defaults: { _controller: BarcoBundle:Register:register }
barco_profile:
    path:     /profile
    defaults: { _controller: BarcoBundle:Register:profile }
barco_login:
    path:     /login
    defaults: { _controller: BarcoBundle:Register:login }
