index:
    resource: "@BarcoBundle/Resources/config/routing.yml"
    prefix:   /

barco:
    resource: "@BarcoBundle/Resources/config/barcoRouting.yml"
    prefix:   /barco

amarre:
    resource: "@BarcoBundle/Resources/config/amarreRouting.yml"
    prefix:   /amarre

accesorio:
    resource: "@BarcoBundle/Resources/config/accesorioRouting.yml"
    prefix:   /accesorio

users:
    resource: "@BarcoBundle/Resources/config/usuarioRouting.yml"
    prefix:   /users

api:
    resource: "@BarcoBundle/Resources/config/apiRouting.yml"
    prefix:   /api

logout:
    path: /logout

app:
    resource: '@AppBundle/Controller/'
    type: annotation
