# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        BarcoBundle\Entity\Usuario: bcrypt


    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: 1234
                        roles: 'ROLE_USER'
        my_db_provider:
          entity:
            class: BarcoBundle:Usuario
            property: username

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        users:
            pattern: ^/
            anonymous: ~
            provider: my_db_provider
            form_login:
                login_path: /login
                check_path: /login
            logout:
                path:   /logout
                target: /

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
                - {path: ^/login,roles: IS_AUTHENTICATED_ANONYMOUSLY}
                - {path: ^/profile,roles: ROLE_USER}
                - {path: ^/barco/addBarco,roles: ROLE_ADMIN}
                - {path: ^/barco/updateBarco/,roles: ROLE_ADMIN}
                - {path: ^/barco/deleteBarco/,roles: ROLE_ADMIN}
                - {path: ^/users,roles: ROLE_ADMIN}
