<?php

namespace BarcoBundle\Repository;

/**
 * AccesorioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccesorioRepository extends \Doctrine\ORM\EntityRepository
{
}
