<?php

namespace BarcoBundle\Repository;

/**
 * AmarreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmarreRepository extends \Doctrine\ORM\EntityRepository
{
}
